# Generated by Django 4.2.27 on 2025-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
    ]
